// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"golang-project-boilerplate/internal/config"
	"golang-project-boilerplate/internal/delivery/http/handler"
	"golang-project-boilerplate/internal/delivery/http/middleware"
	"golang-project-boilerplate/internal/delivery/http/router"
	"golang-project-boilerplate/internal/usecase/auth"
)

// Injectors from wire.go:

// InitializeApp
func InitializeApp() (*App, error) {
	configConfig := config.NewConfig()
	app := config.NewFiber(configConfig)
	logger := config.NewLogger(configConfig)
	authUsecaseContract := auth.NewAuthUsecase(configConfig)
	middlewareMiddleware := middleware.NewMiddleware(logger, authUsecaseContract)
	pingHandler := handler.NewPingHandler()
	route := router.NewRoute(app, middlewareMiddleware, pingHandler)
	lifecycle := NewLifecycle(logger)
	appApp := NewApp(app, configConfig, route, lifecycle)
	return appApp, nil
}

// wire.go:

var configSet = wire.NewSet(config.NewConfig, config.NewFiber, config.NewLogger)

var lifecycleSet = wire.NewSet(
	NewLifecycle,
)

var middlewareSet = wire.NewSet(middleware.NewMiddleware)

var usecaseSet = wire.NewSet(auth.NewAuthUsecase)

var handlerSet = wire.NewSet(handler.NewPingHandler)

var routerSet = wire.NewSet(router.NewRoute)
