// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"golang-project-boilerplate/internal/app"
	"golang-project-boilerplate/internal/config"
	"golang-project-boilerplate/internal/delivery/grpc/handler"
	"golang-project-boilerplate/internal/delivery/grpc/middleware"
	"golang-project-boilerplate/internal/delivery/grpc/server"
)

// Injectors from wire.go:

// InitializeApp
func InitializeApp() (*app.App, error) {
	configConfig := config.NewConfig()
	fiberApp := config.NewFiber(configConfig)
	logger := config.NewLogger(configConfig)
	middlewareMiddleware := middleware.NewMiddleware(logger)
	pingHandler := handler.NewPingHandler()
	grpcServer := server.NewGrpcServer(middlewareMiddleware, pingHandler)
	appApp := app.NewApp(fiberApp, configConfig, grpcServer)
	return appApp, nil
}

// wire.go:

var configSet = wire.NewSet(config.NewConfig, config.NewFiber, config.NewLogger)

var middlewareSet = wire.NewSet(middleware.NewMiddleware)

var handlerSet = wire.NewSet(handler.NewPingHandler)

var appSet = wire.NewSet(server.NewGrpcServer, app.NewApp)
